### ISSUE TITLE
Issue when try to go to next song

### ISSUE THREAD

**Issue by VincentBoots** [michaelherger/spotty#10]
When going to the next song it start over the current song.  So ik keeps repeating its own stream.
when using Spotify connect

**Comment by JohanGroenenboom** [comment]
I observed the same behaviour. Tried the "optimize pre-buffering option as a resolution, but that didn't work.

**Comment by michaelherger** [comment]
Thanks for the report. Unfortunately there seems to be a problem with Spotify's backend-services which are at the root of this problem. It's been reported to Spotify, but no reaction so far. But you are not alone:

https://github.com/spotify/web-api/issues/821#issuecomment-442823565

I tried to work around this issue in a recent Spotty release (2.6.2), but hat workaround only is hiding the problem, without fixing the broken user experience :-(.

**Comment by michaelherger** [comment]
Are you still seeing this behaviour?

**Comment by JohanGroenenboom** [comment]
> Are you still seeing this behaviour?

Just tried it, now it works, did you change anything? or did Spotify?
I'm still running Spotty Spotify 2.6.2
Thanks for the support, keep up the good work!

**Comment by JohanGroenenboom** [comment]
> > Are you still seeing this behaviour?
> 
> Just tried it, now it works, did you change anything? or did Spotify?
> I'm still running Spotty Spotify 2.6.2
> Thanks for the support, keep up the good work!

Sorry, I didn't test thoroughly, apparently it varies with the use case.
It's now back to the old behaviour. I still need to find out what works and what doesn't.
I started from a Spotify playlist, and while I stayed in there, skipping to the next track or some other random track from the list worked fine. But then I did some searches and also played some tracks from my own music library and now it's back to repeating the same track whatever I do.  I will let you know if I have a better reproduction scenario.

**Comment by michaelherger** [comment]
In any case please set logging for plugin.spotty to Info (See Settings/Advanced/Logging). This should give you a lot more information about what is going on with Spotty. 

And please provide step by step instructions to understand what you are doing.

**Comment by Mideam** [comment]
Hello,

I am using spotty v0.12.0, and am experiencing behaviour that may relate to this issue.
I am observing the following while a track is playing:

When skipping to the next track in an album (by tapping the "►|" button):
• slimserver spottyconnect command's _params->_cmd is "change".
• API me/player object's item->uri is different from slimserver song object's streamUrl.
• The next track plays, as expected.

When selecting another track in the album track list:
• slimserver spottyconnect command's _params->_cmd is "change".
• API me/player object's item->uri is the same as slimserver song object's streamUrl.
• The current track stops and resumes, not as expected.

Any info about whether this is the same issue is appreciated.

Thanks

**Comment by michaelherger** [comment]
> I am using spotty v0.12.0, and am experiencing behaviour that may relate to this issue.

That's why you need to update to v0.12.1. Isn't the update offered to you?

**Comment by NeverSimple** [comment]
Mhh.. v0.12.1? I guess you mean v0.13? Or I missed something.

**Comment by michaelherger** [comment]
You can try either of them. I released 0.12.1 with the plugin, as I failed to build 0.13 on all platforms. The latter is up to date with all upstream (librespot) changes, whereas 0.12.1 is based on older code and only has a modification to deal with recent changes on Spotify's end.

**Comment by NeverSimple** [comment]
Oh. I build 0.13 on FreeBSD and have been using that for about two weeks. Didn't know there was anything wrong with it. It build without problems. I didn't even notice 12.1.

**Comment by michaelherger** [comment]
Great if 0.13 works for you! It did work for me on Mac and x86_64 Linux, too, but failed on some ARM based systems. I therefore decided to go the save way and back-port the one change I wanted. And to stick with the same version across all platforms.

**Comment by Mideam** [comment]
> That's why you need to update to v0.12.1. Isn't the update offered to you?

No, the update is not offered to me.
I am using a slimserver plugin that is a fork of the Spotty slimserver plugin.

I confirm that, copying spotty v0.12.1 (i386-linux/spotty-x86_64) from Spotty v2.7.4 to the fork, resolves the issue here.

Thank you for your help.

**Comment by michaelherger** [comment]
What kind of fork? You better trust the original ;-)

**Comment by Mideam** [comment]
It is a fork for a commercially available multi-room HiFi system.

**Comment by michaelherger** [comment]
Tell them to fix their stuff...

**Comment by Mideam** [comment]
No need, because they are reporting the issue to me, so I can investigate.
