### ISSUE TITLE
Mac desktop app and mobile app sync problem w/ LMS

### ISSUE THREAD

**Issue by alen-z** [michaelherger/spotty#11]
Mac desktop app and mobile app don't show currently playing song on LMS after selecting it as a source. Good news is I see LMS as a source (which disappears form time to time unexpectedly but haven't caught the pattern yet).

Will the sync of currently playing song be available in the future?

Proper respect for maintaining this repo,
Alen

**Comment by michaelherger** [comment]
Spotify seems to be changing stuff on their end recently. What Spotty version? What kind of players? How is the data wrong? Tracks behind or ahead?

**Comment by alen-z** [comment]
Thx for the quick response.

iPhone 8.4.79.933
Mac 1.0.95.289.g342899da
LMS 7.7.6 (Squeezebox Duet)
Spotty v2.6.6

When playing, tracks visible only on Duet.

**Comment by michaelherger** [comment]
Please provide step-by-step instructions required to reproduce what you're doing. It's not clear to me what you're doing, seeing, expecting.

**Comment by alen-z** [comment]
I'm on the same network w/ my devices.

Use case #1 (works as expected):
1. Play a song on a Mac
2. Open Spotify on a phone
3. Select Mac as a device
4. See which song is playing, time elapsed, control Mac from phone etc.

Use case #2 (Duet):
1. Play a song on a Duet
2. Open Spotify on a phone
3. Select Duet as a device
4. No changes on a phone. Not showing currently playing song or time elapsed etc.

Use case #3:
1. Open Spotify app on a phone
2. Select Duet as a device
3. Play a song
4. Time elapsed on phone is in front of played song
5. Song shows on a Mac when Duet is selected as a device (time elapsed also in front of actual song)
6. Play a song on Duet
7. Mac and a phone do not see the played song

**Comment by michaelherger** [comment]
I think this is all working as expected: if you control Spotify by selecting content on the Duet (#2), then this will not show up in Spotify apps. All track control is handled by Spotty on LMS. You'd see the play queue in LMS, whereas you cannot see it when controlling from a Spotify app. Unfortunately that's the way it is. I call this "LMS mode" vs. "Connect mode": only in the latter case, when you control Spotty from an official Spotify app you'd be able to control from other Spotify apps.

The slight discrepancy in play time display is a known issue in Connect mode.
