### ISSUE TITLE
Error: Failed to lookup address information

### ISSUE THREAD

**Issue by notDavid** [michaelherger/spotty#12]
Hi there,

i just installed Logitech Media Server on an Ubuntu 18.04 vps, using Spotty 2.6.6.
After entering my Spotify username and password, and clicking "Apply" i saw this error on top of the screen:

`Authorization failed: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("failed to lookup address information: Try again") }) }  `

It took me some time to figure out that unbound (which i had installed as this ubuntu servers dns resolver by following [this guide](https://docs.pi-hole.net/guides/unbound/) ) also listens on port 5353 udp, which appeared to be the same port Spotty was listening on, resulting in breaking dns resolving for the entire server... and also preventing Spotty itself from working:
Spotty crashed with this command: `/var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/Spotty/Bin/i386-linux/spotty-x86_64 -c /var/lib/squeezeboxserver/cache/spotty/__AUTHENTICATE__ -n Spotify\ Authorization\ (servername) -u myusername -p mypassword -a --disable-discovery`).

unbound was listening on:  UDP 127.0.0.1:5353
spotty was listening on: UDP *:5353

Stopping unbound and temporarily setting 1.1.1.1 as a dns resolver solved the problem. After entering the spotty username & password, and disabling "Spotify Connect", Spotty stops listening on 5353 and everything works fine again.

- Just posting as FYI and also in case others stumble upon the same issue (Pi-Hole is quite popular these days) they can then find it here... :-)

**Comment by michaelherger** [comment]
Interesting, thank you! I knew that spotty could conflict with avahi or the like for this reason. But I thought that falling back to disabling announcements and using username/password would get past this. Definitely something to keep in mind. Thanks again!
