### ISSUE TITLE
Stream Spotify podcast 

### ISSUE THREAD

**Issue by pasandal** [michaelherger/spotty#13]
I am not able to stream Spotify podcasts from your application.

Is this a feature you are planning to implement?

Great work on the software.
Thanks,
Paul

**Comment by michaelherger** [comment]
It's something I'd love to support. But Spotify doesn't expose access to Podcasts (and many other features they're offering) in their API. Maybe somebody finds a workaround. But until then I can't do much.

**Comment by michaelherger** [comment]
Podcasts are available in the latest Spotty version..
