### ISSUE TITLE
Librespot changes

### ISSUE THREAD

**Issue by duncanspumpkin** [michaelherger/spotty#14]
Hi I see in your readme it states that you had to modify librespot for it to integrate with spotty. I was just wandering what changes did you have to make and why?

**Comment by michaelherger** [comment]
I need a few features which are not part of librespot. Eg. pipe a single track out, then quit; signal certain events to the Spotty plugin over http; add more event notifications.

As for the actual modifications: just diff my fork (https://github.com/michaelherger/librespot) with the upstream. It's mostly in `playback/src/player.rs`.
