### ISSUE TITLE
Playlist radio repeats same songs but does not load new

### ISSUE THREAD

**Issue by wolfi1234** [michaelherger/spotty#15]
spotty version according to squeezebox server (7.9.1): 2.7.5

Unfortunately, spotty does not work properly when using spotify connect together with the playlist-radio function ("more songs load as you listen"). spotty keeps repeating the same songs instead of loading new ones.

The original librespot implementation has this issue as well. The issue has been fixed, e.g., in the librespot-java fork (https://github.com/librespot-org/librespot-java/commit/e4d80fcf606f6d287561dc0c04434d9b6d0b1a9d).
Could you please have a look at this? It's the basic feature for me and I would totally regret, if I could not use it.

Thanks in advance!
Wolfi

**Comment by michaelherger** [comment]
As you might have seen there currently is a lot of activity going on in librespot. And much of it indeed is about those radio style mixes, podcasts etc. Unfortunately I'm of little help there, just hope I'll be able to implement this in spotty once they've figured it out.
