### ISSUE TITLE
Song is skipped after few seconds and make players out of sync.

### ISSUE THREAD

**Issue by noliveleger** [michaelherger/spotty#16]
Hi @mherger,

After upgrading squeezebox server and spotty, I have this issue described in title. 
When I ask to play the whole album, first song plays for 4-5 seconds and it skips to next one. But players don't start the second one at the same time, so all others songs are played out of sync on the players. 
If I do skip it the first one manually before the errors occurs, all other songs play just fine on each player. 
It can be reproduced with this album: `L'étrange pays`, artist:  `Jean Leloup`

Logitech Media Server Version: 7.9.2 - 1565967976 
Spotty: 2.8.4 
3 players: 
- Odroid C1 with Max2Play / SqueezeLite 
- Raspberry Pi with Max2Play / SqueezeLite
- Old Atom desktop with Ubuntu / SqueezeLite

Spotify Connect: checked for all players.

Before the upgrade I had 
Logitech Media Server Version: 7.9.0 
Spotty: 2.2.x

**Comment by michaelherger** [comment]
Please go to Settings/Advanced/File Types and disable Spotty -> OGG transcoding.

**Comment by noliveleger** [comment]
Thanks a lot. That was it. 
Does it mean I miss some codecs on my ubuntu server?

**Comment by michaelherger** [comment]
It should be there, but unfortunately has proven to be buggy on some platforms.
