### ISSUE TITLE
Error in spotty helper

### ISSUE THREAD

**Issue by Steph71** [michaelherger/spotty#17]
Hi, 

I am running LMS in a docker container form here:

https://github.com/larsks/docker-image-logitech-media-server

which works with no issues up to the point in which I try to install the spotty plugin.

when entering the configuration page in order to setup my spotify account I see the error message below.

Is it true, that spotty doesn't work on x64 systems ? or might it be related to the docker installation ?

Beim Ausführen der Spotty Helfer-Anwendung ist ein Fehler aufgetreten. Vermutlich wird diese auf ihrem System nicht unterstützt. Bitte wenden Sie sich an mich, unter Angabe der folgenden Plattform-Informationen:

Betriebssystem: Debian / x86_64-linux

Ordner für Hilfsprogramme:
/usr/share/squeezeboxserver/Bin/x86_64-linux
/usr/share/squeezeboxserver/Bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/srv/squeezebox/cache/InstalledPlugins/Plugins/Spotty/Bin/i386-linux
/srv/squeezebox/cache/InstalledPlugins/Plugins/Spotty/Bin
ldd (Ubuntu GLIBC 2.23-0ubuntu10) 2.23

**Comment by michaelherger** [comment]
Linux x86_64 certainly should work - I'm using that myself. Docker otoh has been causing problems for quite a few people. Not in the way you are experiencing it, but often eg. players would not be seen by Spotify apps. 

Anyway. Not sure what's wrong with your environment. Could be libc is too old?

**Comment by Steph71** [comment]
tried native installation ... works like charm ....
