### ISSUE TITLE
Got a crash on the first login

### ISSUE THREAD

**Issue by mirh** [michaelherger/spotty#19]
When using plugin.audio.spotify. 
I didn't have problems afterwards, but the exception code worried me enough to post. 
```
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=spotty.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=5aff361f
Sig[3].Name=Fault Module Name
Sig[3].Value=spotty.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5aff361f
Sig[6].Name=Exception Code
Sig[6].Value=c000001d
Sig[7].Name=Exception Offset
Sig[7].Value=0029ac0d
```
Why would your executable return an illegal instruction? (I have a core 2 quad if it can help)
EDIT: [wtf](https://bugzilla.mozilla.org/show_bug.cgi?id=1311868#c22)

**Comment by michaelherger** [comment]
Your "wtf" might indeed explain the issue :-D. Would the authentication itself succeed? Because in such a case the helper would exit deliberately.

**Comment by mirh** [comment]
As I said, nothing seemed wrong (aside of windows telling me spotty crashed (I don't know why VS couldn't open for debug -.-))
I cycled around kodi's menus *just because I guess?* But when I tried to browse again the plugin everything was good.

**Comment by michaelherger** [comment]
ok, thanks for the heads up

**Comment by intika** [comment]
@michaelherger thanks for this amazing app :) 
just a little quick off topic remark, i developed an app based on yours, it could interest you ;)
https://github.com/Intika-Linux-Spotify/Spotimaster
