### ISSUE TITLE
Spotty crashing LMS

### ISSUE THREAD

**Issue by Aigburth** [michaelherger/spotty#20]
I've been running spotty on my Squeezebox network for a long time with no problems. Yesterday the LMS would not connect to my players. I tried to restart LMS but it kept stopping. I managed to open it in safe mode. It will only run in full mode if Spotty is turned off. All other plugins work, including Tidal. As soon as turn Spotty back on the LMS stops.
Any ideas?

**Comment by michaelherger** [comment]
Anything in server.log? What OS are you on? And how long did you let the players try to connect before you gave up?

**Comment by Aigburth** [comment]
[server.log.zip](https://github.com/michaelherger/spotty/files/4416239/server.log.zip)
Windows 7
Tried the whole process about 5 times

**Comment by michaelherger** [comment]
There seems to be some networking problem in your environment:

```Couldn't resolve IP address for: api.spotify.com```

I see many of these warnings. I guess that if you left LMS running for a while, it would recover. But it's super busy trying to authenticate with Spotify and failing. Can you make sure that host name does resolve?

**Comment by Aigburth** [comment]
Same problem just repeats. If I unistall Spotty LMS and players are all OK. If I install Spotty LMS shuts down.
[server.log (1).zip](https://github.com/michaelherger/spotty/files/4431429/server.log.1.zip)

**Comment by michaelherger** [comment]
I'm sorry, I don't see any sign of failure. You seem to have uninstalled the plugin in the end. How would you do that if you weren't able to start LMS with the plugin installed?

**Comment by Aigburth** [comment]
started LMS in safe mode

**Comment by michaelherger** [comment]
Are you using some kind of firewall or similar which might block outgoing traffic?

**Comment by Aigburth** [comment]
Only AVC
I recently reset my router.
I can't remember if some kind of exemptions need to be in place for LMS or Spotty?

**Comment by Aigburth** [comment]
These exemptions are in AVC
c:\programdata\squeezebox\cache\installedplugins\plugins\spotify\bin\mswin32-x86-multi-thread\spotifyd.exe
c:\program files (x86)\squeezebox\server\scanner.exe

**Comment by michaelherger** [comment]
`spotifyd.exe` is from an old Spotify plugin. The Spotty helper is `spotty.exe`.

**Comment by Aigburth** [comment]
so should I delete it?

**Comment by Aigburth** [comment]
[server.log (2).zip](https://github.com/michaelherger/spotty/files/4441298/server.log.2.zip)

**Comment by Aigburth** [comment]
I closed AVG. Now at least LMS starts and stays open with Spotty installed. But now LMS cannot see any players

**Comment by michaelherger** [comment]
Right now you have a networking problem:

> [20-04-06 22:38:32.0597] Slim::Networking::Async::connect (114) Failed to connect to www.mysqueezebox.com1:443, because
Net::HTTP: connect: timeout

You might need to not only "close" AVG, but to get rid of it. We've seen that before...

**Comment by Aigburth** [comment]
Uninstalled AVG
Restarted 
LMS running, connected to players, Spotty working fine
Just worried I have no anti-virus protection now
Thanks Michael

**Comment by michaelherger** [comment]
Wow... that's bad. But there's still Windows Defender. Some say that's all you need, and many AV products would add more issues than they protected you from...
