### ISSUE TITLE
Spotty can't play from Spotify, won't even open in LMS web or app

### ISSUE THREAD

**Issue by kapn1966** [michaelherger/spotty#21]
Spotty has worked great for a year or so, but a couple of weeks ago, music wouldn't play anymore though we could still browse. Assuming some protocol change was the cause, I updated the plugin on LMS and re-added the account. The account add process worked fine, but as soon as I attempt to switch playback to one of the LMS clients, the Spotify display flashes and the client disappears from the "connected devices" list.
Trying the Spotty menu in LMS is worse, it won't display anything.
I have removed, rebooted and re-installed several times to no avail. Looking in the logs shows that there is some kind of connection problem, but not being very familiar with the LMS code, I am at a loss for what the problem might be. Here is a snippet:
```[20-04-01 18:01:21.0400] Plugins::Spotty::API::Token::_killTokenHelper (164) Timed out waiting for a token
[20-04-01 18:01:21.0531] Plugins::Spotty::API::Token::_killTokenHelper (164) Timed out waiting for a token
[20-04-01 18:02:01.0984] Slim::Networking::IO::Select::__ANON__ (147) Error: Select task failed calling Slim::Web::HTTP::processHTTP: Not a SCALAR reference at /volume1/@appstore/SqueezeCenter/Slim/Web/HTTP.pm line 1770.
; fh=Slim::Web::HTTP::ClientConn=GLOB(0xa5b4d10)

I'm running LMS 7.7.6 - 1452060463 on a Synology DS412+
Spotty version 3.1.3
the old Spotify official plugin is NOT installed. Should it be?

**Comment by michaelherger** [comment]
Is there anything blocking the internet access for Spotty? The helper fails to get a session token with a timeout. This usually means it tries to connect to Spotify's servers, but fails to do so within a reasonable amount of time.

(And BTW: your LMS is almost four years old... time to update!)

**Comment by kapn1966** [comment]
A fair comment about my version of LMS. I thought the same, but I've been very busy with other things and it seems that Synology has stopped pulling in the latest version. I'll have to consider my options.
You were right about something blocking requests. I was confused by the fact that other requests seemed to still be coming through the server. In the end I rebooted the entire physical machine and the problem cleared. Sorry to have troubled you. Thanks for making such a valuable plugin for LMS. Can I send you a little thank you via paypal or something?
Keep safe in these crazy times.

**Comment by michaelherger** [comment]
Good to hear this is resolved. 

As for LMS update: there's user pinkdot in the forums.slimdevices.com who provides updated packages for Synology. You might give that a try.
