### ISSUE TITLE
No podcast playback from playlists

### ISSUE THREAD

**Issue by elektronaut69** [michaelherger/spotty#22]
If a playlist contains podcasts, the podcasts are not played back. If playing a mixed playlist, the music is played back correctly but the podcasts are skipped.

**Comment by michaelherger** [comment]
What spotty helper are you using? See Settings/Advanced/Spotty.

**Comment by elektronaut69** [comment]
/usr/local/slimserver/Cache/InstalledPlugins/Plugins/Spotty/Bin/arm-linux/spotty-hf (v0.35.0)

**Comment by elektronaut69** [comment]
BTW: I am using a Raspberry Pi4B as a server running PiCorePlayer. 

I just tested a little further. If you open a playlist containing only podcasts, the playlist does not contain any entries in LMS.

**Comment by michaelherger** [comment]
Can you share a sample URL of such a podcast? And what server.log says when LMS tries to play it?

**Comment by elektronaut69** [comment]
Sorry for not answering immediately. I was on night-shift.
Here are some links. The first one is a mixed playlist containing music and
podcasts. When I start playback on the sb It plays the intro and the music,
but the podcasts are missing in the playlist on my squeezeboxes.
https://open.spotify.com/playlist/37i9dQZF1EfRYm29032AeI?si=fQ--DKnaTfWDA4FZo8o2wA

The second one is a podcasts only playlist. When trying to start playback
on a squeezebox, the playlist on the sb is empty.
https://open.spotify.com/playlist/37i9dQZF1DXde6gsltXMBj?si=Mb7_koFzSfOECRS6MZKO7w

The server.log does not contain any entries.

BTW via Spotify connect I can playback these playlists but playback stops,
when the next entry is a podcast. I can play the podcasts when I hit play
on the Phone. If the next entry is music, playback continues.


Am Mo., 6. Apr. 2020 um 21:34 Uhr schrieb michaelherger <
notifications@github.com>:

**Comment by michaelherger** [comment]
Thanks, those links were very helpful. Turns out Spotify returns what might be invalid data:

```json
    "track" : {
      "disc_number" : 0,
      "duration_ms" : 302002,
      "episode" : false,
      "explicit" : false,
      "external_ids" : {
        "spotify" : "https://open.spotify.com/episode/14VNn9qPQp6tfv6Y6BGsVQ"
      },
      "external_urls" : {
        "spotify" : "https://open.spotify.com/episode/14VNn9qPQp6tfv6Y6BGsVQ"
      },
      "href" : "https://api.spotify.com/v1/episodes/14VNn9qPQp6tfv6Y6BGsVQ",
      "id" : "14VNn9qPQp6tfv6Y6BGsVQ",
      "is_local" : false,
      "is_playable" : false,
      "name" : "Nachrichten vom 10.04.2020, 06:00 Uhr",
      "popularity" : 0,
      "preview_url" : "https://p.scdn.co/mp3-preview/a823823397c96644020ee044eceab2cb63d777a7",
      "track" : true,
      "track_number" : 0,
      "type" : "episode",
      "uri" : "spotify:episode:14VNn9qPQp6tfv6Y6BGsVQ"
    },
```

They do return an `is_playable` flag which is set to `false`. I do filter out such items because that flag should tell me whether the item is playable or not after all... 

I'll see whether I can add a hack to work around this limitation and will raise a bug report on Spotify's account.

**Comment by michaelherger** [comment]
https://github.com/spotify/web-api/issues/1528

**Comment by michaelherger** [comment]
Should be worked around in 4.0.1.

**Comment by michaelherger** [comment]
This actually would have belonged in the [Spotty-Plugin](https://github.com/michaelherger/Spotty-Plugin/issues) repository.
