### ISSUE TITLE
spotty-hf seems to have problems with special characters in passwords

### ISSUE THREAD

**Issue by Halbelunge** [michaelherger/spotty#24]
I had a password with !,$,%,#,' etc.
Some of these characters seems to cause problems. During login the settings Page of LMS promted "Anmeldung fehlgeschlagen" ("Login failed").

Switching to a weaker PW without special characters fixed it for the moment.

**Comment by michaelherger** [comment]
I'm sorry about that. What OS are you on? I thought I had addressed this a while back. I fear it's either the dollar sign, or a quote. Could you narrow it down?

BTW: wouldn't authentication using a Spotify app work?
