### ISSUE TITLE
zombie processes

### ISSUE THREAD

**Issue by Fenix4k** [michaelherger/spotty#26]
hey there

thank you so much for this plugin, it is awesome!

I have noticed that whenever I stop playing from Spotty and go back to my local libraries or just when I turn off my squeezebox, Spotty will leave behind a zombie process. these processes can't be killed until LMS is completely restartet (then they are removed without further interaction)
since my "server" is not that powerful, I do not have the option on to always have a spotty service for my squeezebox started but rather only when needed

anyway to fix that behavior or is this something entirely new?

thanks again and br

**Comment by michaelherger** [comment]
Are you saying there would be an increasing number of those zombies?

**Comment by Fenix4k** [comment]
yes
I just tested it by starting and stopping spotify playback 5 times and i got 10 zombies now
5x spotty <defunct>
5x flac <defunct>

**Comment by michaelherger** [comment]
Do you still see this issue with the latest 1.2.0 helper?

**Comment by michaelherger** [comment]
I'm going to close this issue. Please feel free to open a new report on https://github.com/michaelherger/librespot, where this helper is living now.
