### ISSUE TITLE
Failed to get access token

### ISSUE THREAD

**Issue by ryangodammit** [michaelherger/spotty#33]
When trying to access Spotty via the LMS webpage or thru iPeng I get

Failed to get access token
Please check Settings/Advanced/Spotty Spotify for Squeezebox in the web interface

I tried taking it off and putting it back on, and re-authorising but still the same

Log
   frame 0: Slim::Utils::Log::logBacktrace (/usr/local/slimserver/Slim/Schema/Storage.pm line 121)
   frame 1: Slim::Schema::Storage::throw_exception (/usr/local/slimserver/CPAN/DBIx/Class/Storage/DBI.pm line 1007)
   frame 2: DBIx::Class::Storage::DBI::__ANON__ (/usr/local/slimserver/Slim/Plugin/FullTextSearch/Plugin.pm line 568)
   frame 3: Slim::Plugin::FullTextSearch::Plugin::_initPopularTerms (/usr/local/slimserver/Slim/Plugin/FullTextSearch/Plugin.pm line 137)
   frame 4: Slim::Plugin::FullTextSearch::Plugin::__ANON__ (/usr/local/slimserver/Slim/Control/Request.pm line 2058)
   frame 5: (eval) (/usr/local/slimserver/Slim/Control/Request.pm line 2058)
   frame 6: Slim::Control::Request::notify (/usr/local/slimserver/Slim/Control/Request.pm line 859)
   frame 7: Slim::Control::Request::checkNotifications (/usr/local/slimserver/slimserver.pl line 711)
   frame 8: main::idle (/usr/local/slimserver/slimserver.pl line 680)
   frame 9: main::main (/usr/local/slimserver/slimserver.pl line 1224)

[22-01-08 13:07:40.0062] Slim::Control::Request::notify (2060) Error: Failed notify: Carp::Clan::__ANON__(): DBI Exception: DBD::SQLite::db selectcol_arrayref failed: no such table: fulltext_terms [for Statement "
		SELECT term, d FROM (
			SELECT term, SUM(documents) d
			FROM fulltext_terms
			WHERE NOT col IN ('*', 1, 0) AND LENGTH(term) > 1
			GROUP BY term
			ORDER BY d DESC
		)
		WHERE d > 500
	"] at /usr/local/slimserver/Slim/Schema/Storage.pm line 125
[22-01-08 13:10:21.1993] Plugins::Spotty::API::Token::_killTokenHelper (182) Token refresh call helper has closed unexpectedly? - Please consider re-setting your Spotify credentials should this happen all the time.
[22-01-08 13:10:21.2005] Plugins::Spotty::OPML::__ANON__ (198) Failed to get featured playlists and/or token - do not continue

LMS 8.2.0

**Comment by michaelherger** [comment]
The log you posted is mostly unrelated. I believe this sometimes happens temporarily when there's some hiccup in the communication between LMS/Spotty and the Spotify systems. Does the problem persist?

**Comment by ryangodammit** [comment]
I just checked and yes, still happening 24 hrs later.

How could I post a better log for you? I also seem to be having trouble with piCoreplayers shairport. Could that be related?

**Comment by michaelherger** [comment]
Enable `INFO` logging for `plugin.spotty` to get more verbose log information. Don't use `DEBUG`, as it's super noisy!

Did you try to delete your account and re-authenticate? I've seen cases where the credentials file got corrupted.
