### ISSUE TITLE
LMS Transport

### ISSUE THREAD

**Issue by amsound** [michaelherger/spotty#34]
Hi Michael, are the transport controls on LMS able to control a Spotify Connect stream? 

I've realised when I press next track it looks like it's only going through the playlist (not what's on the phone) which of course there isn't one and my device gets confused. Anything you're able to do or is this just one of these LMS limitations? Thanks

**Comment by michaelherger** [comment]
When you're using Spotty in Connect mode (needs to be enabled in the Spotty settings), then you can control transport from a Spotify app, as well as from SB/LMS. But in that case you only get to see the currently playing track in LMS. And it's limited to one device at a time. And it's a bit fragile... (playback sometimes would "randomly" stop).

**Comment by amsound** [comment]
When you say "needs to be enabled in the Spotty settings" I assume you're referring to Spotify Connect Endpoint? This is enabled yes.

Regarding transport on LMS it 'goes' to the end of the track and the device disconnects. You have had better experiences?

**Comment by michaelherger** [comment]
Yes: I start playback using the Spotify app on my phone. Then I press "Next" on the SB, and I get to hear the next track.

What kind of player are you using?

**Comment by amsound** [comment]
So I'm playing a track on my iPhone on Connect, open LMS web interface press >> and the track stops. My phone shows the track finished with the play bar progress at the end with 0 seconds left and play has stopped.

I have to press next track on my iPhone to continue listening to the playlist I was on to continue playback.

**Comment by michaelherger** [comment]
Are you _playing_ on the phone, or are you only using it to control playback on your LMS, while actually playing on a SB?

**Comment by amsound** [comment]
Yes I’m _playing_ on the phone and wanting to use the transport controls to control it. Is this possible or not, as it’s not working for me at all.

**Comment by michaelherger** [comment]
No, that's not possible. You can only control LMS playback on the LMS connected devices.

**Comment by amsound** [comment]
“Yes: I start playback using the Spotify app on my phone. Then I press "Next" on the SB, and I get to hear the next track.” 

Sorry, I thought you said this was possible? As above?

**Comment by michaelherger** [comment]
It's possible if the Spotify app is connecting to my Squeezebox. It's not possible if the audio is played on the phone itself.

**Comment by amsound** [comment]
Could you clarify what you mean by "It's possible if the Spotify app is connecting to my Squeezebox". Thanks

**Comment by michaelherger** [comment]
The sound will only come out of one device: your phone, or a speaker connected to your Squeezebox. That's what I call the player. But the Spotify app can also be a "controller", controlling playback on other speakers, among which the Squeezebox. In that case you press "play" on your phone, but the sound does not come out of your phone, but some other player.

So... if Squeezebox is the player you're controlling using the Spotify app, then you should be able to press the transport control buttons on that Squeezebox, and they should work.

If your phone is the player, then you can't use the Squeezebox transport control buttons.

**Comment by amsound** [comment]
Michael, I'm really sorry but unfortunately I'm not sure you've understood me all the way through this dialogue. I do understand Spotify Connect with regard to only one device will play the stream/audio.

From my point of view, I want to connect to my Squeezelite player using Spotify Connect. Obviously Logitech Media Server is running your plugin and playing a stream I've initiated via Spotify Connect on my phone. I was hoping the transport controls displayed on my LMS web interface would work and control the Connect stream as other devices I've used with Spotify Connect can _control_ the audio.

Is it true to say your plugin can not be controlled by Logitech Media Server playback controls for what I'm mentioning above? If not, is it something which can be implemented? It currently does not work for me.

If I've not understood your reply, please accept my apologies.

**Comment by michaelherger** [comment]
My answer is still the same as in my very first response, before all the confusion began: Spotty allows you to control back/fwd/pause/volume in Connect mode. If it's not working for you, then there's something specific about your setup.

What system are you running LMS on? Are you using huge buffers in Squeezelite? What Spotty settings are you using?

**Comment by amsound** [comment]
Ok thanks for making that clearer.

LMS is running on Debian 9, players are on a Mac and a PiCore Player on a Raspberry Pi. I haven't adjusted any buffers, Spotty is using default settings, I've applied a client ID to see if it would help but in truth no idea what it's for. Buffer wise I've not adjusted anything. Would you like it to be set to something?

Specs on the server:
Logitech Media Server Version: 8.2.0 - 1627922070 @ Tue Aug 3 11:38:26 CEST 2021
Operating system: Debian - EN - utf8
Platform Architecture: i686-linux
Perl Version: 5.24.1 - i686-linux-gnu-thread-multi-64int
Audio::Scan: 1.02
IO::Socket::SSL: 2.074
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)
Spotty v4.8.1

**Comment by michaelherger** [comment]
I'm a bit lost, tbh. Don't change the buffers. I was asking because sometimes people configure huge buffers, which could accommodate a full album. But those huge buffers can cause problems.

Are the players synced? If so: would you see the same issue with them separated again?

Please enable `INFO` logging for `plugin.spotty` (see Settings/Advanced/Logging). Do your thing to reproduce the issue, then provide a copy of your server.log.zip (feel free to upload to https://www.dropbox.com/request/T3RctyzGgNg0oFDubq6a).

**Comment by amsound** [comment]
Michael, I can't explain it however it's now working. Does it rely on Mysqueezebox.com as I had to update certificates recently.

**Comment by michaelherger** [comment]
No, Spotty has nothing to do with MySB.
