### ISSUE TITLE
Multi Account Support

### ISSUE THREAD

**Issue by jukey** [michaelherger/spotty#7]
I would like to configure more than one Spotify account at the same time. This was possible using the original Spotify plugin for Squeezebox but seems to be impossible using spotty.

Do you have any plans to support more than one account in the future?

**Comment by michaelherger** [comment]
Multi-account management has been part of the Spotty plugin from very early on. Just go to the settings screen and add another account.

**Comment by jukey** [comment]
Thanks for pointing out! Awesome news. :) Maybe it is worth having an "Add Account" menu item in the device UI that points out how to add another account (e.g. "Go to web config and add an account there")?

**Comment by michaelherger** [comment]
I'm not planning to enhance the player menu, as most users in multi-user environments seem to prefer the Connect mode anyway.

**Comment by jukey** [comment]
What's the connect mode?

**Comment by michaelherger** [comment]
You can have Spotty announce your SB players as Spotify Connect endpoints. They will then show up in the Spotify apps and desktop applications as devices you can play on. This means you'd control your SB from the Spotify app, rather then the LMS environment.

**Comment by michaelherger** [comment]
https://www.spotify.com/connect/

**Comment by jukey** [comment]
Thanks for your explanation! Now I enabled this feature as well. Did not see it before.
