### ISSUE TITLE
Error during initial Spotify Account setup

### ISSUE THREAD

**Issue by jukey** [michaelherger/spotty#8]
I am running the lms on an rasperry pi running raspian os, latest version.I enabled the Spotty Plugin, restarted the lms and now I get the following error, when I try to access the config page for the plugin:

```
404 Not Found: plugins/Extensions/settings/plugins/Spotty/settings/basic.html
```
Do you know how to solve this?

**Comment by michaelherger** [comment]
Don't know why this happens on some installations. I've never been able to reproduce it. But whatever: just go to Settings/Advanced/Spotty. The "dead" link is only a shortcut to the same place.
