### ISSUE TITLE
After upgrade of the plugin clients can no longer connect

### ISSUE THREAD

**Issue by reneklootwijk** [michaelherger/spotty#9]
I updated the plugin to version 2.1.11 and the spotty helper application to version 0.9.1. I run on freenas. When I specify a connect player on the Spotify client is tries to connect but fails. On console of the lms server I see the following error each time a client tries to connect:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(13))', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

I tried with the old version of the helper application, 0.8.1, same results.

It used to work before the upgrade of the plugin.

**Comment by michaelherger** [comment]
Spotify has changed something on their end which requires an update of librespot (the library being used by spotty). See https://github.com/librespot-org/librespot/issues/181.

Did you build the binary yourself? You'd have to build from the [dev](https://github.com/michaelherger/spotty/tree/dev) branch rather than master. I'll merge them as soon as I see it working reliably.

**Comment by reneklootwijk** [comment]
I build the dev branch and indeed it seems to work allright again.

**Comment by reneklootwijk** [comment]
I can play songs on all players and multi-user also works. However, I cannot stop playing a song. The button in the Spoitfy client changes to stopped, but the music keeps on playing.

**Comment by michaelherger** [comment]
Good to know the build does work.

Unfortunately yes, there's some problem with the pausing. It's not consistent, and I'm having a hard time trying to understand why it fails. From my POV it's correctly telling LMS to pause. But LMS doesn't. I'm working on it.

**Comment by michaelherger** [comment]
I'm closing this issue, as the main issue is resolved. Thanks!
